server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://terraform-20241113145123008000000001.c5gi2ggeg9db.us-west-1.rds.amazonaws.com:5432/urlShortenerDb
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: create